# Generated by Django 3.2.15 on 2023-03-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('googleplus_link', models.URLField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
