# Generated by Django 3.2.15 on 2023-03-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeddyBear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('Aristobear', 'Aristobear'), ('Regency Bears', 'Regency Bears'), ('Aurelia Bears', 'Aurelia Bears'), ('Evermore Bears', 'Evermore Bears'), ('Ambrosia Bears', 'Ambrosia Bears'), ('Luminous Bears', 'Luminous Bears'), ('Celestine Bears', 'Celestine Bears'), ('Nimbus Bears', 'Nimbus Bears'), ('Lavender Lane Bears', 'Lavender Lane Bears'), ('Verdant Valley Bears', 'Verdant Valley Bears'), ('Crimson Peak Bears', 'Crimson Peak Bears'), ('Belle Époque Bears', 'Belle Époque Bears')], max_length=255)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('bear_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('bear_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('bear_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('bear_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('bear_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('color', models.CharField(choices=[('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('golden', 'Golden'), ('cream', 'Cream'), ('beige', 'Beige'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('purple', 'Purple'), ('gray', 'Gray')], max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('material', models.CharField(choices=[('cotton', 'Cotton'), ('wool', 'Wool'), ('plush', 'Plush'), ('synthetic', 'Synthetic')], max_length=20)),
                ('features', models.CharField(choices=[('moveable arms', 'Moveable arms'), ('moveable legs', 'Moveable legs'), ('button eyes', 'Button eyes'), ('embroidered eyes', 'Embroidered eyes'), ('satin bow', 'Satin bow'), ('growler', 'Growler'), ('jingle bell', 'Jingle bell'), ('ribbon', 'Ribbon'), ('heart-shaped nose', 'Heart-shaped nose'), ('paw pads', 'Paw pads'), ('bean filling', 'Bean filling'), ('jointed', 'Jointed')], max_length=255)),
                ('recommended_age', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
