# Generated by Django 3.2.15 on 2023-04-01 00:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teddyBears', '0002_auto_20230331_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teddybear',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
