# Generated by Django 3.2.15 on 2023-04-01 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teddyBears', '0004_alter_teddybear_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teddybear',
            options={'ordering': ['id']},
        ),
    ]
