# Generated by Django 3.2.15 on 2023-04-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teddyBears', '0005_alter_teddybear_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teddybear',
            old_name='bear_photo3',
            new_name='bear_photo_3',
        ),
    ]
