# Generated by Django 3.2.15 on 2023-04-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyBears', '0006_rename_bear_photo3_teddybear_bear_photo_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='teddybear',
            name='tag',
            field=models.CharField(blank=True, choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('new_arrival', 'New Arrival'), ('limited_edition', 'Limited Edition')], max_length=50, null=True),
        ),
    ]
