# Generated by Django 3.2.15 on 2023-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyBears', '0007_teddybear_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teddybear',
            name='tag',
            field=models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('New Arrival', 'New Arrival'), ('Limited Edition', 'Limited Edition')], max_length=50, null=True),
        ),
    ]
